FROM php:8.3-apache

RUN apt update && apt install -y git vim telnet \
    && docker-php-ext-install mysqli pdo pdo_mysql \
    && cp "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

WORKDIR /var/www
RUN git clone https://github.com/votre-repo.git html

CMD ["apache2-foreground"]