
services:
  mariadb:
    image: mariadb
    container_name: c_mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=tartempion
      - MARIADB_DATABASE=mabase
      - MARIADB_USER=myuser
      - MARIADB_PASSWORD=mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
 
  monapache:
    image: docker73dj/monapache
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - SERVEUR_BD=mariadb
      - NOM_BD=${MARIADB_DATABASE}
      - USER_BD=${MARIADB_USER}
      - MDP_BD=${MARIADB_PASSWORD}

  monubuntu:
    image: docker73dj/monubuntu


