version: '3.8'

services:
  
  mariadb:
    image: mariadb
    container_name: c_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d  
      - ./bd_data:/var/lib/mysql           
    ports:
      - "3306:3306"
    networks:
      - my_network

  
  apache:
    image: php:8.3-apache
    container_name: c_apache
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html  
    networks:
      - my_network
    depends_on:
      - mariadb  
    environment:
      - SERVEUR_BD=c_mariadb
      - NOM_BD=${MARIADB_DATABASE}
      - UTILISATEUR_BD=${MARIADB_USER}
      - MDP_BD=${MARIADB_PASSWORD}

  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: c_phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: c_mariadb
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - my_network
    depends_on:
      - mariadb

  
  monubuntu:
    build:
      context: .
      dockerfile: Dockerfile.monubuntu
    image: monubuntu
    container_name: c_ubuntu
    restart: always
    networks:
      - my_network
    command: tail -f /dev/null  
    tty: true
    stdin_open: true

networks:
  my_network:
    driver: bridge
